const tone = require('.')

ipa('diəm˧˩˨')
ipa('cɤ̆n˧˧')
ipa('ɲɤ˨˦')
ipa('uj˧˩˨')
ipa('è.ɣì.ɣɔ̀')
ipa('àá.fá')
ipa('àà.k͡pɔ̃̀') // ?
ipa('àá.ɾĩ́')
ipa('āá.sì.kí')
ipa('áásìkiriìmù')
ipa('āá.ʃáà.ī.tà')
ipa('àà.wɛ̀')
ipa('àà.jò')
ipa('ʊ̄.mɔ̃̄.lɛ̀')
ipa('jà.ú.jà.úù')
ipa('ka̠ɡa̠sʰʌ̹ŋd͡ʑa̠')
ipa('ˈka̠ːɡa̠ɦa̠da̠')
ipa('ka̠ɡa̠βo̞βo̞')
ipa('săw˧˩˨')
ipa('sɤ̆p˨ˀ˩')
ipa('ʔɗəwk͡p̚˧˨ʔ')
ipa('ɑb̥eˈd̥isə')

call('byu^dy')
call('diU--U-m')
call('ky~O!n')
call('ny~O-O+')
call('uu--u-y')
call('e-Qi-Qo$-')
call('a-a+fa+')
call('a-a-kpo$&-')
call('a-a+ri&+')
call('aa+si-ki+')
call('a+a+si-kiri-imu-')
call('aa+xa+a-ita-')
call('a-a-wE-')
call('a-a-yo-')
call('Omo$&lE-')
call('ya-u+ya-u+u-')
call('ka@ga@sh~Uqdjy~a@')
call('ka@_ga@hha@da@')
call('ka@ga@VoVo')
call('sa!a--a-w')
call("sO-!O--p'!")
call('oia')
call('oyawi')
call('blartxUnnak')
call('sOfIstUkeytId')
call('suprkAlUfrAdjUlIstIkEkspiAlOdoxOs')
call('spri^qkl')

function call(a) {
  const syllables = tone.syllable(a)
  console.log('call => ' + a)
  console.log('  font => ' + tone(a))
  console.log('  mark => ' + syllables.count)
  console.log('  free => ' + syllables.free)
}

function ipa(a) {
  console.log('ipa => ' + a)
  console.log('  call => ' + tone.pronunciation(a))
}
