import tone from './index.js'

make('byu^dy')
make('diU--U-m')
make('ky~O!n')
// make('ny~O-O+')
// make('uu--u-y')
// make('e-Qi-Qo$-')
// make('a-a+fa+')
// make('a-a-kpo$&-')
// make('a-a+ri&+')
// make('aa+si-ki+')
// make('a+a+si-kiri-imu-')
// make('aa+xa+a-ita-')
// make('a-a-wE-')
// make('a-a-yo-')
// make('Omo$&lE-')
// make('ya-u+ya-u+u-')
// make('ka@ga@sh~Uqdjy~a@')
// make('ka@_ga@hha@da@')
// make('ka@ga@VoVo')
// make('sa!a--a-w')
// make("sO-!O--p'!")
// make('oia')
// make('oyawi')
// make('blartxUnnak')
// make('sOfIstUkeytId')
// make('suprkAlUfrAdjUlIstIkEkspiAlOdoxOs')
// make('spri^qkl')

function make(a: string) {
  console.log('text => ' + a)
  console.log('  font => ' + tone.make(a))
}
